name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: sitespeed.io Demo.js --multi --html.pageSummaryMetrics -n1 
      - name: Download container
        uses: ishworkh/docker-container-artifact-download@v1
        with:
          path: ./Reports
