name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Test Connectivity - 2
      run: |
        ping -c 10 192.168.56.1
    - name: Test Connectivity - 2
      run: |
        ping -c 10 192.168.0.33
    #- name: Running sitespeed.io container
      #run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.host 100.64.77.217 --influxdb.port 8086 --influxdb.username admin --influxdb.Welcome1 --influxdb.database siteSpeedDB --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
