name: Remote ssh command
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: Build command
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
                bash /opt/git/my-repository/update.sh
#     - name: Running sitespeed.io container
#       run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.host ${{ secrets.M_HOST }} --influxdb.port 8086 --influxdb.username ${{ secrets.M_USER_DB }} --influxdb.password ${{ secrets.M_PASSWORD_DB }} --influxdb.database ${{ secrets.DB_NAME }} --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
