name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: Step 2 - Add artifacts to publish to the temp folder
        run: cd downloads
      - name: Step 3 - Code checkout
        uses: actions/checkout@v3
      - name: Step 4 - Running sitespeed.io container
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --multi -n1
      - name: Setup InfluxDB
        uses: influxdata/influxdb-action@v3
        with:
          influxdb_version: 1.8.4-alpine
          influxdb_org: influxdata
          influxdb_user: admin
          influxdb_password: Welcome1
          influxdb_bucket: dummy
