name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Test Connectivity
      run: |
        ping -c 10 192.168.0.33
   # - name: Running sitespeed.io container
    #  run: docker run --shm-size=1g --rm -p 8086:8086 -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.database dummy --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
