name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup SSH Action
      uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        SSHKEY: ${{ secrets.M_SECRET }}
        NAME: 192.168.0.94
    - name: Running sitespeed.io container
      run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.host 192.168.0.94 --influxdb.port 8086 --influxdb.username admin --influxdb.password Welcome1 --influxdb.database siteSpeed --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
