name: Remote ssh command
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.M_HOST }}
        username: ${{ secrets.M_USERNAME }}
        key: ${{ secrets.M_KEY_ED25519 }}
        passphrase: ${{ secrets.M_PHRASE }}
        script: |
          cd script/
          sh """docker run --rm -v "$(WORKSPACE):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --multi --browsertime.visualMetrics true -n1"""
#     - name: Running sitespeed.io container
#       run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.host ${{ secrets.M_HOST }} --influxdb.port 8086 --influxdb.username ${{ secrets.M_USER_DB }} --influxdb.password ${{ secrets.M_PASSWORD_DB }} --influxdb.database ${{ secrets.DB_NAME }} --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
