name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --multi --html.pageSummaryMetrics -n1 
      - name: Docker Image Artifact Download
        # You may pin to the exact commit or the version.
        # uses: ishworkh/docker-image-artifact-download@a88e9adfcb7add4c13f495c159a963ed8ec1b95a
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: sitespeed.io:latest
