name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: Step 2 - Add artifacts to publish to the temp folder
        run: cd downloads
      - name: Step 3 - Code checkout
        uses: actions/checkout@v3
      - name: Step 4 - Running sitespeed.io container
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --network=my-net --influxdb.host 192.168.0.33 --influxdb.port 8086 --influxdb.database siteSpeedDB --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=11_28_2022
