name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: sitespeed.io Demo.js --multi --html.pageSummaryMetrics -n1 
      - name: Download a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: sitespeed
          path: ./Result
