name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --network=my-net --influxdb.host 192.168.56.1 --influxdb.port 8086 --influxdb.database siteSpeedDB --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=11_23_2022
