name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Setup SSH Action
      uses: fifsky/ssh-action@v0.0.6
      with:
        key: ${{ secrets.M_SECRET }}
        host: 192.168.0.94
        command: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
