name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Make TCP Connection
      uses: BGarber42/action-tcp-connection@1.0.0
      with:
        # IP to connect to
        remotehost: 192.168.0.33
        # Port to connect to
        remoteport: 8086
   # - name: Running sitespeed.io container
    #  run: docker run --shm-size=1g --rm -p 8086:8086 -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:latest Demo.js --influxdb.database dummy --multi --browsertime.visualMetrics true -n1 --influxdb.tags category=test,date=12_05_2022
